[package]
name = "trebuchet"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "LICENSE"
authors = ["Emmett Rayes <emmett.rayes@icloud.com>"]

[workspace]
members = ["lib"]

[dependencies]
